### ISSUE TITLE
Problem running the bot

### ISSUE THREAD

**Issue by Tanasa25P** [Pandasswap/Pancakeswap-Prediction-Bot#4]
Hi I tried to follow the instructions but when I try to run the bot i get this errors, can you help me fix it? Thank you 
![1](https://github.com/Pandasswap/Pancakeswap-Prediction-Bot/assets/138524486/22609153-6a53-4f08-81c3-e9c14dd227fa)

**Comment by Pandasswap** [comment]
Try to ran the bot on Linux.

**Comment by Tanasa25P** [comment]
Same results 
![image](https://github.com/Pandasswap/Pancakeswap-Prediction-Bot/assets/138524486/00b9989f-ef8b-46f1-a933-dacd272cfc59)

**Comment by Pandasswap** [comment]
That’s weird..

**Comment by Pandasswap** [comment]
[https://stackoverflow.com/questions/77071456/typeerror-web3-is-not-a-constructor](url)
Try this
